#!/usr/bin/env python
import sys
import os
import shutil
import glob

build_dir = 'build'
includes_dir = 'includes'
descs_path = '%s/sample_descs.rst' % build_dir

print("Building sample READMEs...")

print("  Setting up the build.")
if os.path.exists(build_dir):
    shutil.rmtree(build_dir)
os.makedirs(build_dir)

print "  Generating READMEs:"
files_to_process = glob.glob('*.rst')

# open the sample descriptions file.
sdesc_file = open(descs_path, 'w+')

for filename in files_to_process:
    # Make README.md for each sample
    (basename, extension) = os.path.splitext(os.path.basename(filename))
    print "   * %s" % basename
    os.system('rst2html.py %s >%s/%s.html' % (filename, build_dir, basename))
    os.system('pandoc -t markdown_github %s/%s.html -o ../%s/README.md' %
            (build_dir, basename, basename))

    # Make sample descriptions

    # write the title
    sdesc_file.write('%s\n%s\n\n' % (basename, '~' * len(basename)))
    # write the description
    sdesc_file.write('.. include:: ../%s/%s_desc.rst\n\n' % (includes_dir,
        basename.lower()))
    # link to the sample directory
    sdesc_file.write('Sample code + description: `%s <%s/>`_\n\n' % (basename,
        basename))

sdesc_file.close()

# now, generate the master README
print "   * master README"
os.system('rst2html.py includes/BASE_README.rst >%s/README.html' % build_dir)
os.system('pandoc -t markdown_github %s/README.html -o ../README.md' %
        build_dir)

print "Finished!"

