--- 
application_stack: 
  components: 
    database: 
    - id: database1
      host: host1
    - id: database2
      host: host2
    - id: database3
      host: host3
    app_server: 
    - id: app_server1
      host: host1
      database: 
      - database1
      - database2
    - id: app_server2
      host: host3
      database: 
      - database3	
    web_server: 
    - id: web_server1
      host: host1
      database: 
      - database1
      - database2
      app_server: 
      - app_server1
      - app_server2
    load_balancer: 
    - id: load_balancer1
      host: host1
      web_server: 
      - web_server1
  frontend_component:
    - load_balancer1
